version: "3.9"

services:
  app:
    container_name: delayed_notifier_app
    build: .
    ports:
      - "7540:7540"
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped
    volumes:
      - ./web:/app/web


  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq_server
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"  
      - "15672:15672" 
    restart: unless-stopped
